### PR TITLE
first-commit

### PR DESCRIPTION
**Pull request by deepur126**

### CODE REVIEW

**Comment by vinaykumarpoosala** [comment]
Not added any new files??

**Comment by vinaykumarpoosala** [comment]
'''Not added any'''

**Comment by deepur126** [comment]
committed new packages dao, beans, dbtransaction change db into dynamic than static. review for db changes in dao package @vinaykumarpoosala  @AnushkaRani

**Comment by deepur126** [comment]
Files uploaded for employee login, customer creation & home jsp
with css files
@vinaykumarpoosala @rishabh-verma-au3 @AnushkaRani

**Review by deepur126 — COMMENTED** [review]
Version changes are present

**Pull request closed without merging**
